# Generated by Django 2.1.3 on 2021-08-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addressType',
            new_name='_method',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='contactPersonName',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='contactPersonNumber',
            new_name='contact_person_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='method',
            new_name='contact_person_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='userId',
            new_name='user_id',
        ),
    ]
