# Generated by Django 2.1.3 on 2021-08-24 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_auto_20210820_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_discount_amount', models.FloatField()),
                ('coupon_discount_title', models.CharField(max_length=100)),
                ('order_amount', models.FloatField()),
                ('order_type', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=11)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('order_note', models.CharField(max_length=200)),
                ('coupon_code', models.CharField(max_length=11)),
                ('restaurant_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
