# Generated by Django 2.1.3 on 2021-08-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20210825_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetaill',
            old_name='product',
            new_name='products',
        ),
    ]
