# Generated by Django 2.1.3 on 2021-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20210825_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
