# Generated by Django 2.1.3 on 2021-08-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20210825_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order'),
        ),
    ]
